---
title: "Simulation Study-1"
author: "Wei-Chen Chang"
date: "`r Sys.Date()`"
output: 
  html_document:
     toc: true
     toc_depth: 2
     toc_float: true
     code-link: true
     code-tools: true
     code_folding: show
     code_download: true
     code-overflow: "scroll"
     self-contained: true
     number_sections: false
     df_print: paged
bibliography: "CPT_LA_new.bib"  
csl: "apa.csl"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	fig.align = "center",
	warning = FALSE,
	rows.print=11,
	paged.print=TRUE
)
```


```{r lib, message=FALSE, include=FALSE}
library(tidyverse)
library(glue)
library(magrittr)
library(patchwork)
library(kableExtra)
# import functions
source("../functions/player_and_lotteries.R")
source("../functions/analysis_functions.R")
# ggplot settings
theme_set({
  theme_bw()+    
  theme(
    legend.position = "bottom",
    legend.title = element_text(size = 17),
    legend.text = element_text(size = 17),
    axis.title = element_text(size = 16),
    axis.text.x = element_text(vjust = 0.5, hjust = 0.5),
    axis.text = element_text(size = 13),
    strip.text= element_text(size = 12),
    title = element_text(size = 18))
})
```


# Simulation Setting(Code Part)

```{r params}
# Simulation Parameters
Nsim <-  1000L
.phi <-  0.0367 # err = 1e-8, 0.027513126 is err = 1e-6
param <-  list("alpha"=.88, "beta"=.88, "lambda"=2.25, "wp"=.5, "wn"=.5)
exp_param <- list(
  init_values =
    list("G"= 2000L,
         "g"=300L, "l"=-300L, "x1+"=1000L),
  random_init = FALSE,
  fix_bnd_width = FALSE,
  n_est = 3L + (6*2L),
  min_step = 0L,
  step_size = 320L
)
mix_param <- list(
  est_method = "ASA", # changed method type: ASA, UD
  start_crit = 500L, # Bisection 3 Times
  start_step = 100L, # ASA_c = 2*100
  stop_rev_times = 3L,
  UseMidrunEst = TRUE 
) 
phi_vec <- c(.phi*10, .phi, .phi*0.1)
names(phi_vec) <- c("large", "medium", "small")
```

## Directories

```{r dir_params}
dir_name <- "./ASA_simulation_RDS"
pic_path <- "./figs"
```

# Simulation 1 (new version)


```{r bound2}
file_name <- "Study1_df.RDS"
fname <- file.path(dir_name, file_name)

bound_df <- read_rds(fname) %>% 
  rename(method = method_type) %>% 
  select(phi, method, alpha:lambda, Nsim, any_of("early_stop"),
         matches("^x[1-9](pos|neg)_est")) %>% 
  rename_with(\(x) str_remove(x, "_est")) %>% 
  mutate(
    method = sub("Bisection_Slider", "Bisection-Slider", method)
  ) %>% 
  add_column(x0 = 0L, .before = "x1pos")

# Count the invalid points
bound_df %>%
  group_by(method, lambda, phi) %>%
  summarise(
    num_Inf = sum(rowSums(across(x1pos:x6neg, is.infinite)) > 0),
            .groups = 'drop') %>% 
  filter(num_Inf!=0) %>%
  print()

# Add true value
bound_df <- bound_df %>%
  # Filter invalid data points
  filter(!rowSums(across(x1pos:x6neg, is.infinite)) > 0) %>%
  nest(data = !c(alpha:lambda)) %>%
  rowwise() %>%
  mutate(
    truev = list(
      find_optimal_params(
        params = list(
          "alpha" = alpha, "beta" = beta, "lambda" = lambda, "wp" = 0.5, "wn" = 0.5
          ),
        exp_params_init = exp_param$init_values,
        x_num = exp_param$n_est)
      )
    ) %>%
  ungroup() %>%
  unnest_wider(truev, names_sep = "_") %>%
  select(!matches("truev_(L(_2)?|G_2|lambda_KW)$")) # L, L2 G2 orlambdaKW

# unnest and pivot_longer
true_df <- bound_df %>%
  add_column(truev_x0 = 0) %>% 
  pivot_longer(
    cols = starts_with("truev"), 
    names_to = "utility",
    values_to = "true_value") %>% 
  mutate(utility = utility |>
           str_remove("^truev_")|>
           factor(labels = -6:6,
                  levels =
                    c(paste0("x", 6:1, "neg"),
                      "x0",
                      paste0("x", 1:6, "pos")))
         ) %>% 
  select(!data)

cleaned_df <- bound_df %>%
  select(alpha:data) %>% 
  unnest() %>%
  utility_longer() %>% 
  left_join(true_df, by = join_by(alpha, beta, lambda, utility))

```



## Utility Curve Plots

顏色線段代表 95% 的觀測值分布範圍長度。黑色虛線為實際數值

```{r, fig.height=7, fig.width=14}
cleaned_df %>% 
  filter(lambda == 2.25 & phi != "small") %>%
  mutate(
    method =
      factor(
        method,
        levels =
          c("ASA", "ASA_randInit",
            "Bisection","Bisection_fixbnd",
            "Bisection-Slider", "Bisection-Slider_fixbnd",
            "MOBS", "MOBS_fixbnd",
            "SimpBisection", "SimpBisection_randInit",
            "PEST", "PEST_randInit")
      )
  ) %>%
  group_by(phi) %>% 
  ggplot(aes(y = utility)) +
  geom_hline(
    yintercept = 
      as.numeric(
        factor("x0", levels = gen_util_levels()
               )),
    color = "red2",
    linetype = "dashed", alpha = 0.8) +
  # True utility curve
  geom_line(
    aes(y = utility, x = true_value, group = 1),
    color = "black", linetype = "3331") +
  geom_point(
    aes(y = utility, x = true_value, group = 1),
    color = "black", pch = 1, size =2.5) +
  # 95% range
  stat_summary(
    aes(y = utility, x = x_value, color = phi, shape = phi),
    geom = "pointrange",
    fun = \(x) mean(x, na.rm = TRUE),
    fun.min = \(x) quantile(x, .025, na.rm = TRUE),
    fun.max = \(x) quantile(x, .975, na.rm = TRUE),
    position = position_dodge(width = 0.9),
    linewidth = 1.1, size = 0.6, alpha=.8
  ) +
  labs(x = "Elicited x ",
       y = "Values",
       title = "Value Curve",
       color = "phi") +
  facet_wrap(~ method, dir="v", ncol=6, nrow=2) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 0.6, vjust=0.6),
    strip.text= element_text(size = 15),
    )

pname <- "study1_utility_curve.pdf"
save_fig(pname, width = 14, height = 7)
```

## Bias and RMSE

```{r summ_biasRMSE}
df.bias_RMSE <- cleaned_df %>%
  filter(utility != 0) %>% 
  mutate(
    boundary_type = case_when(
      grepl(".*_fixbnd$", method) ~ "fix_bnd",
      grepl(".*_randInit$", method) ~ "rand_init",
      TRUE ~ "equal_exp"
    ),
    method = 
      str_replace(method, "_(randInit|fixbnd)$", "") |>
      factor(
        levels = 
          c("ASA", "Bisection", "Bisection-Slider", 
            "MOBS", "SimpBisection", "PEST")
      )
  ) %>% 
  group_by(phi, method, boundary_type, utility, lambda) %>% 
  summarise(
   bias = mean(x_value - true_value)|> round(),
   RMSE = 
     (x_value - true_value)^2 |> 
     mean() |>
     sqrt() |>
     round(),
   .groups = "drop"
   )
```

### Bias

```{r bias_bnd, fig.height=7, fig.width=13}
p.bias <- df.bias_RMSE %>% 
  filter(lambda == 2.25) %>% 
  ggplot(aes(x = utility)) +
  geom_line(aes(
    x = utility,
    y = bias,
    color = boundary_type,
    group = boundary_type),
    linewidth = 1.2,
    alpha = 0.8
    ) +
  geom_hline(yintercept = 0, color = "grey30", lty=2, alpha=0.8)+
  geom_point(
    aes(
      y = bias,
      color = boundary_type,
      shape = boundary_type),
    size = 3) +
  facet_grid(rows = vars(phi),
             cols = vars(method),
             # scales = "free_y"
             ) +
  scale_x_discrete(labels = latex_labels) +
  scale_color_discrete(
    # values = c("fix_bnd" = "cyan4", "equal_exp" = "orange2"),
    labels = c("fix_bnd" = "Boundary Width = 5000",
               "equal_exp" = "Equal Expectation",
               "rand_init" = "Random Initial"),
    name = "Variants") +
  scale_shape_manual(
    values = c("fix_bnd" = 16, "equal_exp" = 17, "rand_init" = 15),
    labels = c("fix_bnd" = "Boundary Width = 5000",
               "equal_exp" = "Equal Expectation",
               "rand_init" = "Random Initial"),
    name = "Variants") +
  labs(x = expression(x["i"]),
       y = "Bias",
       title = "Bias")+
  theme(
    strip.text= element_text(size = 15)
    )

pname <- "study1_bias.pdf"
p.bias
save_fig(pname, width = 13, height = 7)
```


### Bias2

Vary in $\lambda$ in the value function.

-   3 levels: 0.5, 1, 2.25.

```{r bias_vary_lambda, fig.height=14, fig.width=14}
df.tmp <- cleaned_df %>%
  filter(utility != 0) %>% 
  mutate(
    method = case_when(
      method == "Bisection_Slider" ~ "Bisection-Slider",
      method == "Bisection_Slider_fixbnd" ~ "Bisection-Slider_fixbnd",
      TRUE ~ method # Keep other values unchanged
    )
    ) %>% 
  group_by(phi, method, utility, lambda) %>% 
  summarise(
   bias = mean(x_value - true_value)|> round(),
   RMSE = (x_value - true_value)^2 |> 
     mean() |>
     sqrt() |>
     round(),
   .groups = "drop"
   )
helper_plot <- function(df) {
  df %>% ggplot(aes(x = utility)) +
  geom_line(aes(
    x = utility,
    y = bias,
    color = lambda,
    group = lambda),
    linewidth = 1.2,
    alpha = 0.8
    ) +
  geom_hline(yintercept = 0, color = "grey30", lty=2, alpha=0.8)+
  geom_point(
    aes(
      y = bias,
      color = lambda,
      shpae = lambda),
    size = 3) +
  scale_color_brewer(palette = "Dark2")+
  facet_grid(rows = vars(phi),
             cols = vars(method),
             # scales = "free_y"
             ) +
  ylim(-6000, 8000)+
  scale_x_discrete(labels = latex_labels) +
  labs(x = expression(x["i"]),
       y = "Bias")+
  theme(
    strip.text= element_text(size = 14)
    )
}

p1 <- df.tmp %>% 
  filter(grepl("(Bisection|MOBS)", method) & !grepl("(Simp)", method)) %>% 
  mutate(lambda = as.factor(lambda),
         method = factor(
           method,
           levels = c("Bisection", "Bisection_fixbnd",
                      "Bisection-Slider", "Bisection-Slider_fixbnd",
                      "MOBS", "MOBS_fixbnd")
           )) %>%
  helper_plot()

p2 <- df.tmp %>% 
  mutate(lambda = as.factor(lambda)) %>%
  filter(!(grepl("(Bisection|MOBS)", method) & !grepl("(Simp)", method))) %>% 
  helper_plot()

p <- p1 / p2 +
  plot_annotation(title = 'Bias (Varies with Lambda)') +
  plot_layout(guides = 'collect') & 
  theme(legend.position='bottom',
        legend.text = element_text(size=15))
p
pname <- "study1_bias_different_Lambda.pdf"

save_fig(pname, width = 14, height = 14)
```


```{r rm, include=FALSE}
rm(df.tmp)
rm(p1)
rm(p2)
```


### RMSE

```{r RMSE_bnd, fig.height=7, fig.width=13}
p.RMSE <- df.bias_RMSE %>% 
  filter(lambda == 2.25) %>% 
  ggplot(aes(x = utility)) +
  geom_line(aes(
    x = utility,
    y = RMSE,
    color = boundary_type,
    group = boundary_type),
    linewidth = 1.2,
    alpha = 0.8
    ) +
  geom_hline(yintercept = c(0), color = "grey30", lty=2, alpha=0.8)+
  geom_point(
    aes(
      y = RMSE,
      color = boundary_type,
      shape = boundary_type),
    size = 3) +
  facet_grid(rows = vars(phi),
             cols = vars(method),
             # scales = "free_y"
             ) +
  scale_x_discrete(labels = latex_labels) +
  scale_color_discrete(
    # values = c("fix_bnd" = "cyan4", "equal_exp" = "orange2"),
    labels = c("fix_bnd" = "Boundary Width = 5000",
               "equal_exp" = "Equal Expectation",
               "rand_init" = "Random Initial"),
    name = "Variants") +
  scale_shape_manual(
    values = c("fix_bnd" = 16, "equal_exp" = 17, "rand_init" = 15),
    labels = c("fix_bnd" = "Boundary Width = 5000",
               "equal_exp" = "Equal Expectation",
               "rand_init" = "Random Initial"),
    name = "Variants") +
  labs(x = expression(x["i"]),
       y = "RMSE",
       title = "RMSE")+
  theme(
    strip.text= element_text(size = 15)
    )

pname <- "study1_RMSE.pdf"
save_fig(pname, width = 13, height = 7)
```



## Bias+RMSE Combined

```{r, fig.height=14, fig.width=14}
p <- p.bias / p.RMSE +
  plot_annotation(
    title = 'Study1: Iterates Until Step Size < 5',
    theme = theme(plot.title = element_text(size = 32, hjust = .5))) +
  plot_layout(guides = 'collect') & 
  theme(legend.position='bottom',
        legend.text = element_text(size = 24),
        legend.title = element_text(size = 26),
        strip.text= element_text(size = 20),
        axis.title.x = element_text(size = 20),
        )

pname <- "study1_biasRMSE.pdf"
p
save_fig(pname, width = 16, height = 16)

```


## Step Count

```{r eval=FALSE, include=FALSE}
len_df <- read_rds(fname) %>% 
  select(alpha:Nsim, ends_with("len")) %>%
  mutate(
    method = str_replace(method_type, "_(randInit|fixbnd)$", ""),
    variant = ifelse(
        grepl(".*_fixbnd$", method_type),
        "fix_bnd",
        ifelse(
          grepl(".*_randInit$", method_type),
          "rand_init",
          "equal_exp")
        ),
    .after = phi,
    .keep = "unused"
  )

len_df %>% 
  group_by(phi, lambda,  method, variant) %>% 
  filter(lambda ==2.25) %>% 
  mutate(
    mean_each_step = rowMeans(across(ends_with("len"))),
    .keep = "unused"
  ) %>%
  summarise(
    mean_step = mean(mean_each_step) |> round(),
    .groups = "drop"
  ) %>% 
  select(!lambda)
  # write_csv(
  #   file = file.path(pic_path, "step.csv")
  # )

```


# Additional Analysis: Loss aversion

## Preprocess

```{r true_LA, eval=FALSE, include=FALSE}
# compute True LA coef. values
trueLA_df <- bound_df %>% 
  select(!data) %>% 
  mutate(KW = - truev_x1pos / truev_x1neg) %>% 
  pivot_longer(cols = matches(".*[1-9][pos|neg]"),
                 names_to = c("trial", "type"),
                 names_pattern = "x(\\d)(.*)",
                 values_to = "value") %>%
  mutate(
    trial = as.integer(trial),
    type = ifelse(type == "pos", "gain", "loss")  # Assign gain/loss
  ) %>% 
  pivot_wider(names_from = type, values_from = value) %>%
  nest(data = c(trial, gain, loss))

trueLA_df <- trueLA_df %>% 
  mutate(
    KT = map(data, ~KT2(.x)),
    .keep = "unused"
    ) %>% 
  unnest_wider(KT, names_sep = "_") %>% 
  pivot_longer(cols = KW:KT_median,
               names_to = "LA_type",
               values_to = "true_LA_est") %>% 
  rename(true_KT_classification = "KT_classification")
```